import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Website Kerja Praktek",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-3 md:mx-10 mt-3 md:mt-10 mb-3 md:mb-10 border-solid border-white border-2 md:border-4 h-screen rounded-2xl">
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
